mount fixado. desmontar e montar volume agora um pouco mais simples e transparente

diff --git a/binme b/binme
--- a/binme
+++ b/binme
@@ -4,6 +4,6 @@ then
 	echo "bin me usage: binme [name of the file to be bin'd] [bin'd file name]"
 	exit 1
 else
-	ls $(pwd)/$1 2>/dev/null && sudo ln -s $(pwd)/$1 /usr/bin/$2 2>/dev/null || ls $1 2>/dev/null && sudo ln -s $1 /usr/bin/$2 2>/dev/null|| echo "an error has ocurred"
+	ls $(pwd)/$1 2>/dev/null && sudo ln -s $(pwd)/$1 /usr/bin/$2 2>/dev/null || ls $1 2>/dev/null && sudo ln -s $1 /usr/bin/$2 2>/dev/null || echo "an error has ocurred"
 	echo "binme: symlink /usr/bin/$2 created successfully"
 fi
