wallpaper aprimorado. typos fixados.

diff --git a/binme b/binme
--- a/binme
+++ b/binme
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
-if [ -z $1 ]
+if [ -z $1 -a -z $2 ]
 then
-	echo "bin me usage: binme [file name]"
+	echo "bin me usage: binme [name of the file to be bin'd] [bin'd file name]"
 	exit 1
 else
-	ls $(pwd)/$1 2>/dev/null && ln -s $(pwd)/$1 /usr/bin/$1  || ls $1 2>/dev/null && ln -s $1 /usr/bin/$1 || echo "inserted file was not found"
+	ls $(pwd)/$1 2>/dev/null && sudo ln -s $(pwd)/$1 /usr/bin/$2 2>/dev/null || ls $1 2>/dev/null && sudo ln -s $1 /usr/bin/$2 2>/dev/null|| echo "an error has ocurred"
+	echo "binme: symlink /usr/bin/$2 created successfully"
 fi
diff --git a/wallpaper b/wallpaper
--- a/wallpaper
+++ b/wallpaper
@@ -1,4 +1,15 @@
-#!/usr/bin/env bash
-WALLPAPER=$HOME/Pictures/wallpaper
-feh --bg-scale $WALLPAPER/indiopara.jpg 2> /dev/null | echo "failure to load wallpaper. something happaned"
-pkill compton 2> /dev/null
+#!/usr/bin/env bash 
+WPP_NAME=wallpaper
+
+if [ -z $1 ]; then
+	F_WPP=$HOME/pictures/wallpaper/$WPP_NAME
+else
+	F_WPP=$1
+	cp $1 ./$WPP_NAME && mv $WPP_NAME $HOME/pictures/$WPP_NAME
+fi
+
+if [ -a $F_WPP ]; then
+	feh --bg-scale $F_WPP 2> /dev/null || echo "wpp: failure loading $F_WPP. something happened"
+else
+	echo "wpp: specified file does not or no longer exists"
+fi
